# Form implementation generated from reading ui file 'Dangky.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dangky(object):
    def setupUi(self, Dangky):
        Dangky.setObjectName("Dangky")
        Dangky.resize(308, 277)
        self.centralwidget = QtWidgets.QWidget(parent=Dangky)
        self.centralwidget.setObjectName("centralwidget")
        self.tbnDK = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tbnDK.setGeometry(QtCore.QRect(120, 150, 71, 31))
        self.tbnDK.setObjectName("tbnDK")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.label_2.setObjectName("label_2")
        self.mk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.mk.setGeometry(QtCore.QRect(120, 70, 151, 20))
        self.mk.setObjectName("mk")
        self.tk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tk.setGeometry(QtCore.QRect(120, 40, 151, 20))
        self.tk.setObjectName("tk")
        Dangky.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Dangky)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 308, 18))
        self.menubar.setObjectName("menubar")
        Dangky.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Dangky)
        self.statusbar.setObjectName("statusbar")
        Dangky.setStatusBar(self.statusbar)

        self.retranslateUi(Dangky)
        QtCore.QMetaObject.connectSlotsByName(Dangky)

    def retranslateUi(self, Dangky):
        _translate = QtCore.QCoreApplication.translate
        Dangky.setWindowTitle(_translate("Dangky", "Đăng ký"))
        self.tbnDK.setText(_translate("Dangky", "Đăng ký"))
        self.label.setText(_translate("Dangky", "Tài khoản:"))
        self.label_2.setText(_translate("Dangky", "Mật khẩu:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dangky = QtWidgets.QMainWindow()
    ui = Ui_Dangky()
    ui.setupUi(Dangky)
    Dangky.show()
    sys.exit(app.exec())
