# Form implementation generated from reading ui file 'qlngdung.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_qlnguoidung(object):
    def setupUi(self, qlnguoidung):
        qlnguoidung.setObjectName("qlnguoidung")
        qlnguoidung.resize(500, 433)
        self.centralwidget = QtWidgets.QWidget(parent=qlnguoidung)
        self.centralwidget.setObjectName("centralwidget")
        self.tobdoanvien = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobdoanvien.setGeometry(QtCore.QRect(110, 0, 111, 31))
        self.tobdoanvien.setObjectName("tobdoanvien")
        self.toboatdong = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toboatdong.setGeometry(QtCore.QRect(220, 0, 91, 31))
        self.toboatdong.setObjectName("toboatdong")
        self.tobdangxuat = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobdangxuat.setGeometry(QtCore.QRect(430, 0, 71, 31))
        self.tobdangxuat.setObjectName("tobdangxuat")
        self.tobchidoan = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobchidoan.setGeometry(QtCore.QRect(0, 0, 111, 31))
        self.tobchidoan.setObjectName("tobchidoan")
        self.tobnguoidung = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobnguoidung.setGeometry(QtCore.QRect(310, 0, 121, 31))
        self.tobnguoidung.setObjectName("tobnguoidung")
        self.Timngdung = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Timngdung.setGeometry(QtCore.QRect(160, 70, 171, 20))
        self.Timngdung.setObjectName("Timngdung")
        self.btnSuatkngdung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSuatkngdung.setGeometry(QtCore.QRect(350, 120, 71, 21))
        self.btnSuatkngdung.setObjectName("btnSuatkngdung")
        self.tkngdung = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tkngdung.setGeometry(QtCore.QRect(160, 120, 171, 20))
        self.tkngdung.setObjectName("tkngdung")
        self.btnXoatkngdung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoatkngdung.setGeometry(QtCore.QRect(350, 150, 71, 21))
        self.btnXoatkngdung.setObjectName("btnXoatkngdung")
        self.tbnTimngdung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tbnTimngdung.setGeometry(QtCore.QRect(350, 50, 71, 21))
        self.tbnTimngdung.setObjectName("tbnTimngdung")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 120, 111, 21))
        self.label.setObjectName("label")
        self.mkngdung = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.mkngdung.setGeometry(QtCore.QRect(160, 150, 171, 20))
        self.mkngdung.setObjectName("mkngdung")
        self.btnThemtkngdung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThemtkngdung.setGeometry(QtCore.QRect(350, 80, 71, 21))
        self.btnThemtkngdung.setObjectName("btnThemtkngdung")
        self.dstk = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.dstk.setGeometry(QtCore.QRect(10, 190, 481, 191))
        self.dstk.setObjectName("dstk")
        self.dstk.setColumnCount(0)
        self.dstk.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 111, 21))
        self.label_2.setObjectName("label_2")
        self.Tkiemdoanvien = QtWidgets.QLabel(parent=self.centralwidget)
        self.Tkiemdoanvien.setGeometry(QtCore.QRect(80, 70, 71, 21))
        self.Tkiemdoanvien.setObjectName("Tkiemdoanvien")
        qlnguoidung.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=qlnguoidung)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 18))
        self.menubar.setObjectName("menubar")
        qlnguoidung.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=qlnguoidung)
        self.statusbar.setObjectName("statusbar")
        qlnguoidung.setStatusBar(self.statusbar)

        self.retranslateUi(qlnguoidung)
        QtCore.QMetaObject.connectSlotsByName(qlnguoidung)

    def retranslateUi(self, qlnguoidung):
        _translate = QtCore.QCoreApplication.translate
        qlnguoidung.setWindowTitle(_translate("qlnguoidung", "ql người dùng"))
        self.tobdoanvien.setText(_translate("qlnguoidung", "Quản lý Đoàn viên"))
        self.toboatdong.setText(_translate("qlnguoidung", "Hoạt động"))
        self.tobdangxuat.setText(_translate("qlnguoidung", "Đăng xuất"))
        self.tobchidoan.setText(_translate("qlnguoidung", "Quản lý Chi đoàn"))
        self.tobnguoidung.setText(_translate("qlnguoidung", "Quản lý người dùng"))
        self.btnSuatkngdung.setText(_translate("qlnguoidung", "Sửa"))
        self.btnXoatkngdung.setText(_translate("qlnguoidung", "Xóa"))
        self.tbnTimngdung.setText(_translate("qlnguoidung", "Tìm"))
        self.label.setText(_translate("qlnguoidung", "Tài khoản:"))
        self.btnThemtkngdung.setText(_translate("qlnguoidung", "Thêm "))
        self.label_2.setText(_translate("qlnguoidung", "Mật khẩu:"))
        self.Tkiemdoanvien.setText(_translate("qlnguoidung", "Tìm kiếm:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qlnguoidung = QtWidgets.QMainWindow()
    ui = Ui_qlnguoidung()
    ui.setupUi(qlnguoidung)
    qlnguoidung.show()
    sys.exit(app.exec())
