# Form implementation generated from reading ui file 'taotk.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_taotk(object):
    def setupUi(self, taotk):
        taotk.setObjectName("taotk")
        taotk.resize(467, 389)
        self.centralwidget = QtWidgets.QWidget(parent=taotk)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 101, 21))
        self.label_2.setObjectName("label_2")
        self.tbntao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tbntao.setGeometry(QtCore.QRect(180, 190, 71, 31))
        self.tbntao.setObjectName("tbntao")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 80, 101, 21))
        self.label.setObjectName("label")
        self.taotk_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.taotk_2.setGeometry(QtCore.QRect(180, 80, 151, 20))
        self.taotk_2.setObjectName("taotk_2")
        self.taomk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.taomk.setGeometry(QtCore.QRect(180, 110, 151, 20))
        self.taomk.setObjectName("taomk")
        taotk.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=taotk)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 467, 18))
        self.menubar.setObjectName("menubar")
        taotk.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=taotk)
        self.statusbar.setObjectName("statusbar")
        taotk.setStatusBar(self.statusbar)

        self.retranslateUi(taotk)
        QtCore.QMetaObject.connectSlotsByName(taotk)

    def retranslateUi(self, taotk):
        _translate = QtCore.QCoreApplication.translate
        taotk.setWindowTitle(_translate("taotk", "Tạo TK"))
        self.label_2.setText(_translate("taotk", "Mật khẩu:"))
        self.tbntao.setText(_translate("taotk", "Tạo"))
        self.label.setText(_translate("taotk", "Tài khoản:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    taotk = QtWidgets.QMainWindow()
    ui = Ui_taotk()
    ui.setupUi(taotk)
    taotk.show()
    sys.exit(app.exec())
