# Form implementation generated from reading ui file 'trangchu.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_trangchu(object):
    def setupUi(self, trangchu):
        trangchu.setObjectName("trangchu")
        trangchu.resize(502, 393)
        self.centralwidget = QtWidgets.QWidget(parent=trangchu)
        self.centralwidget.setObjectName("centralwidget")
        self.tobchidoan = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobchidoan.setGeometry(QtCore.QRect(0, 0, 111, 31))
        self.tobchidoan.setObjectName("tobchidoan")
        self.tobdoanvien = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobdoanvien.setGeometry(QtCore.QRect(110, 0, 111, 31))
        self.tobdoanvien.setObjectName("tobdoanvien")
        self.toboatdong = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toboatdong.setGeometry(QtCore.QRect(220, 0, 91, 31))
        self.toboatdong.setObjectName("toboatdong")
        self.tobnguoidung = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobnguoidung.setGeometry(QtCore.QRect(310, 0, 121, 31))
        self.tobnguoidung.setObjectName("tobnguoidung")
        self.tobdangxuat = QtWidgets.QToolButton(parent=self.centralwidget)
        self.tobdangxuat.setGeometry(QtCore.QRect(430, 0, 71, 31))
        self.tobdangxuat.setObjectName("tobdangxuat")
        trangchu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=trangchu)
        self.statusbar.setObjectName("statusbar")
        trangchu.setStatusBar(self.statusbar)

        self.retranslateUi(trangchu)
        QtCore.QMetaObject.connectSlotsByName(trangchu)

    def retranslateUi(self, trangchu):
        _translate = QtCore.QCoreApplication.translate
        trangchu.setWindowTitle(_translate("trangchu", "Trang chủ"))
        self.tobchidoan.setText(_translate("trangchu", "Quản lý Chi đoàn"))
        self.tobdoanvien.setText(_translate("trangchu", "Quản lý Đoàn viên"))
        self.toboatdong.setText(_translate("trangchu", "Hoạt động"))
        self.tobnguoidung.setText(_translate("trangchu", "Quản lý người dùng"))
        self.tobdangxuat.setText(_translate("trangchu", "Đăng xuất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trangchu = QtWidgets.QMainWindow()
    ui = Ui_trangchu()
    ui.setupUi(trangchu)
    trangchu.show()
    sys.exit(app.exec())
